# Generated by Django 3.2.4 on 2022-04-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_alter_hashesmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashesmodel',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
